apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  annotations:
    # ğŸ”¥ [åŠ å…¥é€™è¡Œ] å‘Šè¨´ Reloaderï¼šåªè¦ configmap æˆ– secret è®Šäº†ï¼Œå°±é‡å•Ÿæˆ‘
    reloader.stakater.com/auto: "true"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate # å¤šæ©Ÿå°±å¯ä»¥æ”¹å› RollingUpdate äº†ï¼Œä¸ç”¨æ–·ç·š
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      # è€ƒæ…®åŠ å…¥é™åˆ¶affinityä¾†è·Ÿk8sèªªchat podä¸è¦æ”¾åŒä¸€å€‹node
      containers:
      - name: chat-service
        image: neo1202/chat-service # éƒ¨ç½²ç”¨
        ports:
        - containerPort: 8080
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SECRET
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: POSTGRES_SSLMODE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_SSLMODE
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
  - port: 8080
    targetPort: 8080