apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config  # 這個名字很重要，等一下要引用
  namespace: default # 我們明確寫出 namespace，讓你更有感覺
data:
  # 這裡放所有的全域設定
  GOOGLE_CLIENT_ID: "189871282006-gml6na5q64t9hb35echhcpiu7k3qco4d.apps.googleusercontent.com" # 這個被看到沒差，像是銀行id
  APP_ENV: "development"