apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  # 資料庫密碼
  POSTGRES_PASSWORD: "password"
  # JWT 簽章密鑰 (兩邊後端要用同一把)
  JWT_SECRET: "my_secret_key_12345"
  # Google Client Secret (雖然目前 Implicit Flow 用不到，但為了以後擴充先放著)
  GOOGLE_CLIENT_SECRET: "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"